/* =====================================================================
   Every project on the site. To add one: copy a block, change the words,
   drop screenshots in assets/shots/ (and run the resize step for tiles),
   and it appears in the gallery, the filters and the case viewer.

   cats:     app · store · web · dash · tool · lab   (filter chips)
   size:     '' (third) · 'half' · 'wide' (two-thirds)
   chips:    short labels shown under the tile
   stats:    [number, label] pairs shown big in the case viewer
   features: [title, description] pairs — the "what's inside" grid
   cover:    browser (d = desktop shot, m = phone shot) · phones · phone · sky · gum · type
   gallery:  { t:'d' desktop | 'm' phone | 'scene', src, label }
   ===================================================================== */
(function () {
  const S = n => `assets/shots/${n}.webp`;
  const W = n => `assets/wall/${n}.webp`;
  const T = n => `assets/tiles/${n}.webp`;

  /* ---------- the Pakiza admin dashboard: its 19 themes and its screens ---------- */
  window.DASH = {
    themes: [
      ['light', 'Light', '☀️', '#1B7A3D'], ['dark', 'Dark', '🌙', '#3DBE74'], ['pink', 'Pink', '🌸', '#E85D9A'],
      ['batman', 'Batman', '🦇', '#F5C518'], ['superman', 'Superman', '🦸', '#1E5BFF'], ['ironman', 'Iron Man', '🦾', '#C8102E'],
      ['flash', 'Flash', '⚡', '#FFB000'], ['loki', 'Loki', '🐍', '#2E8B57'], ['vegeta', 'Vegeta', '👑', '#5B3FD0'],
      ['spiderman', 'Spider-Man', '🕷️', '#D0021B'], ['terminator', 'Terminator', '🤖', '#FF3B30'], ['matrix', 'Matrix', '💊', '#00D95F'],
      ['vader', 'Vader', '🌑', '#9B111E'], ['hulk', 'Hulk', '💪', '#5DBB3F'], ['thor', 'Thor', '🔨', '#7FB3FF'],
      ['bond', '007', '🍸', '#C9A227'], ['harrypotter', 'Harry Potter', '🪄', '#B8860B'], ['deadpool', 'Deadpool', '🗡️', '#B0141E'],
      ['xmen', 'X-Men', '🧬', '#F2C300'],
    ].map(([id, label, icon, color]) => ({ id, label, icon, color, src: S(`pth-${id}-d`) })),
    pages: [
      ['orders', 'Orders'], ['tracking', 'Live rider tracking'], ['leaderboard', 'Rider leaderboard'], ['riders', 'Riders'],
      ['vehicles', 'Vehicles'], ['zones', 'Delivery zones'], ['payouts', 'Rider payouts'], ['reports', 'Reports'],
      ['stock-ledger', 'Stock ledger'], ['purchase-orders', 'Purchase orders'], ['audit-logs', 'Audit log'],
      ['notifications', 'Notifications'], ['offers', 'Offers'], ['approvals', 'Approvals'], ['customers', 'Customers'],
      ['inventory-products', 'Products'], ['inventory-categories', 'Categories'], ['low-stock-alerts', 'Low-stock alerts'],
      ['returns', 'Returns'], ['settings', 'Settings'], ['suppliers', 'Suppliers'],
    ].map(([id, label]) => ({ id, label, path: id.replace('inventory-', 'inventory/'), src: S(`ppg-${id}-d`), thumb: T(`ppg-${id}-d`) })),
  };

  // Hero wall: desktop screens from across the work, including themed dashboards.
  window.WALL = [
    'veloura-home', 'pth-batman', 'violeta-home', 'live-ahk-home', 'reve-home', 'live-duakhana-home',
    'pth-matrix', 'leaner', 'skyforge', 'ppg-tracking', 'veloura-story', 'bareeqs-gate',
    'pth-ironman', 'violeta-services', 'reve-story', 'live-ahk-shop', 'pth-spiderman', 'velvet-site',
    'veloura-product', 'reve-measure', 'pth-light', 'violeta-about', 'ppg-leaderboard', 'pth-vader',
  ].map(W).concat(['assets/pakiza-home.webp', W('walkie-m'), W('yapgap-m'), W('pth-dark-m')]);

  window.PROJECTS = [
    {
      id: 'pakiza-mart', name: 'Pakiza Mart', kind: 'Android + iOS app', cats: ['app'], size: 'wide', live: true,
      color: '#0E4A2C', url: 'Google Play',
      chips: ['Live on Google Play', '60+ categories', 'Light + dark'],
      tagline: 'A grocery delivery app for Pakiza Mart — live on Google Play.',
      lead: 'A full grocery delivery app for Pakiza Mart, a neighbourhood grocery in Gujranwala. Customers browse 60+ categories, search, add to cart and order for delivery with cash on delivery. One backend feeds the app and the shop dashboard.',
      stats: [['Live', 'on Google Play'], ['60+', 'categories'], ['1000+', 'products'], ['2', 'platforms']],
      features: [
        ['Smart home screen', 'Time-of-day greeting, pick of the day, sliding promo banners, and On Sale / Best Sellers / Budget filters.'],
        ['Real checkout', 'Delivery fee that drops to free over Rs 1,500, delivery-slot picker, self-pickup, promo codes, cash on delivery.'],
        ['Order tracking', 'Every order lands in the shop dashboard; customers follow it from placed to delivered.'],
        ['Accounts', 'Email login, profile photo, saved addresses, favourites and in-app account deletion.'],
        ['Push notifications', 'Firebase Cloud Messaging for order updates on Android and iOS.'],
        ['Two themes', 'Light and dark, emerald / gold / cream brand, custom fonts and an animated splash.'],
      ],
      facts: [
        '<b>Approved for Google Play production</b> after 12 testers × 14 days of closed testing.',
        '<b>iOS build running</b>, login token stored in the Keychain / Keystore.',
        '<b>Store listing art generated in code</b> — all 8 Play Store screenshots made with Python.',
      ],
      stack: ['Flutter', 'Dart', 'Provider', 'Firebase', 'Secure storage'],
      link: { href: 'https://play.google.com/store/apps/details?id=com.pakizamart.pakiza_mart', label: 'Get it on Google Play' },
      cover: { type: 'phones', phones: ['assets/pakiza-categories.webp', 'assets/pakiza-home.webp', 'assets/pakiza-detail.webp'] },
      gallery: [
        { t: 'm', src: 'assets/pakiza-home.webp' }, { t: 'm', src: 'assets/pakiza-categories.webp' },
        { t: 'm', src: 'assets/pakiza-detail.webp' }, { t: 'm', src: 'assets/pakiza-placed.webp' },
      ],
    },
    {
      id: 'sober-review', name: 'Sober Review', kind: 'Flutter app', cats: ['app', 'lab'],
      color: '#1C1D4F', url: '',
      chips: ['Offline-first', 'Signature animation'],
      tagline: 'Record ideas at 2 a.m. Judge them sober at 9 — joined by a 1.6-second sunrise.',
      lead: 'An idea vault built around one feeling: night-brain genius versus morning-brain honesty. Recording happens in a glowing night of stars and glass; reviewing happens in harsh clinical morning light.',
      stats: [['1.6s', 'sunrise transition'], ['0', 'accounts needed'], ['100%', 'offline']],
      features: [
        ['Night mode', 'Record voice ideas in a glowing star field; they are saved instantly on the phone.'],
        ['Morning review', 'Swipe each idea to keep or bin, with hand-rolled spring physics.'],
        ['The sunrise', 'A 1.6-second transition between the two worlds — the signature moment.'],
        ['Share card', 'Turn a kept idea into a 1080×1920 card for stories.'],
      ],
      stack: ['Flutter', 'Riverpod', 'sqflite', 'CustomPainter', 'Spring physics'],
      cover: { type: 'sky' },
      gallery: [{ t: 'scene', html: '<div class="sky" style="position:absolute;inset:0"><div class="sky__stars"></div><div class="sky__moon"></div><div class="sky__sun"></div><div class="sky__hills"></div><div class="idea idea--night"><span class="mono">02:14 · Voice note</span><p>“An app that judges my ideas… while I sleep.”</p></div><div class="idea idea--day"><span class="mono">09:02 · Sober review</span><p>“An app that judges my ideas… while I sleep.”</p><div class="verdict"><span>✕ Bin</span><span>✓ Keep</span></div></div><span class="sky__time mono"></span></div>' }],
    },
    {
      id: 'pakiza-admin', name: 'Pakiza Admin', kind: 'Custom dashboard', cats: ['dash'], size: 'half', live: true,
      color: '#17130A', url: 'admin.pakizawp.cloud',
      chips: ['19 themes', '22+ screens', 'Live'],
      tagline: 'The dashboard that runs the whole shop — in 19 themes, from Light to Batman.',
      lead: 'Everything behind the grocery app: new orders ring in, riders are assigned and tracked live, stock and suppliers are managed, and every staff member only sees what their role allows. And because a dashboard you stare at all day shouldn’t be boring, it ships with 19 themes.',
      stats: [['19', 'themes'], ['22+', 'screens'], ['25', 'permission modules'], ['Live', 'admin.pakizawp.cloud']],
      features: [
        ['New-order alerts', 'A bell, a toast and a sound the moment an app order lands — and confetti for the day’s first order.'],
        ['Live rider tracking', 'Riders, vehicles, delivery zones, a rider leaderboard, payouts and a rider audit trail.'],
        ['Stock that adds up', 'Stock ledger, stock movements, purchase orders from suppliers, low-stock alerts and returns.'],
        ['Roles & permissions', 'Owner, manager and viewer plus custom roles, with a tick-grid across 25 modules.'],
        ['Audit log', 'Every change is recorded — who did what, and when.'],
        ['19 themes that rename everything', 'Not just colours: in Batman, riders become “Knights of Gotham”, the tracking map the “Bat-Signal Map”, the leaderboard the “Hall of Heroes” and the shop “The Batcave”. Iron Man, Matrix, Vader, Spider-Man, Thor, 007 and more each get their own world.'],
      ],
      facts: [
        '<b>Live on my own server</b> with HTTPS, alongside its API at api.pakizawp.cloud.',
        '<b>Security-hardened:</b> rate-limited logins, hashed OTPs, server-side order totals.',
        '<b>Photos on Cloudflare R2</b> — upload in the dashboard, appear in the app instantly.',
        '<b>One-command rollback</b>: backup → snapshot → deploy → smoke test.',
      ],
      stack: ['Next.js', 'TypeScript', 'TanStack Query', 'Node + Express', 'Prisma', 'Docker', 'Kamal'],
      cover: { type: 'browser', d: S('pth-batman-d'), m: S('pth-ironman-m') },
      gallery: [
        { t: 'd', src: S('pth-batman-d'), label: 'Dashboard — Batman theme' },
        { t: 'd', src: S('pth-light-d'), label: 'Dashboard — Light theme' },
        { t: 'd', src: S('pth-matrix-d'), label: 'Dashboard — Matrix theme' },
        { t: 'd', src: S('ppg-tracking-d'), label: '/tracking' },
        { t: 'd', src: S('ppg-orders-d'), label: '/orders' },
        { t: 'd', src: S('ppg-leaderboard-d'), label: '/leaderboard' },
        { t: 'd', src: S('ppg-riders-d'), label: '/riders' },
        { t: 'd', src: S('ppg-stock-ledger-d'), label: '/stock-ledger' },
        { t: 'd', src: S('live-padmin-login-d'), label: 'admin.pakizawp.cloud — live' },
        { t: 'm', src: S('pth-dark-m') }, { t: 'm', src: S('pth-ironman-m') }, { t: 'm', src: S('pth-spiderman-m') },
      ],
    },
    {
      id: 'veloura', name: 'Veloura', kind: 'Cap brand website', cats: ['store', 'web', 'dash'], size: 'half',
      color: '#4A1320', url: 'veloura',
      chips: ['Brand website', 'Story-first', 'Admin console'],
      tagline: 'A story-first brand website for a Pakistani cap label — every drop told like a story.',
      lead: 'Veloura is a two-person headwear brand. The website sells the story before the cap: who made it, why, and how — then a shop and product pages that feel like the brand. Behind it sits an admin console built to accounting standards.',
      stats: [['6', 'caps per drop'], ['5', 'story pages'], ['1', 'audited order door']],
      features: [
        ['Story-first pages', 'Home, Story and Craft pages that sell the brand before the product.'],
        ['Shop & product pages', 'A filterable shop and product pages with the story behind each cap.'],
        ['Scroll animation engine', 'Hand-built Drift, Magnetic, Reveal and Ticker scroll scenes.'],
        ['Forensic admin console', 'Orders, inventory, customers, reviews, analytics and an audit trail.'],
        ['Money you can trust', 'Prices are whole-paisa integers; floating-point maths fails the build.'],
        ['Mobile app', 'A React Native companion app for the same brand.'],
      ],
      stack: ['Next.js 15', 'TypeScript', 'Prisma', 'PostgreSQL', 'Redis', 'Tailwind'],
      cover: { type: 'browser', d: S('veloura-home-d'), m: S('veloura-home-m') },
      gallery: [
        { t: 'd', src: S('veloura-home-d'), label: 'Home' }, { t: 'd', src: S('veloura-product-d'), label: 'Product' },
        { t: 'd', src: S('veloura-shop-d'), label: '/shop' }, { t: 'd', src: S('veloura-story-d'), label: '/story' },
        { t: 'd', src: S('veloura-craft-d'), label: '/craft' },
        { t: 'm', src: S('veloura-home-m') }, { t: 'm', src: S('veloura-product-m') },
      ],
    },
    {
      id: 'violeta', name: 'Dr Violeta García Tello', kind: 'Clinic website · client', cats: ['web'], size: 'wide',
      color: '#8C5F74', url: 'dravioletatello.com',
      chips: ['Bilingual ES / EN', 'Own CMS', 'Client · KONO'],
      tagline: 'A bilingual website and brand system for a plastic-surgery clinic.',
      lead: 'Client work through KONO: a calm, editorial site for a surgeon in Mexico City — Spanish and English, services, journal, consultations — with a built-in CMS so the clinic can publish on its own.',
      stats: [['2', 'languages'], ['1', 'CMS for the clinic'], ['Full', 'brand package']],
      features: [
        ['Bilingual', 'Complete Spanish and English sites, each with its own URLs.'],
        ['Services', 'Facial, body, non-surgical and consultation pages with their own detail views.'],
        ['Journal', 'A blog the clinic writes in, in both languages.'],
        ['Content management', 'Pages, services and articles editable in a built-in admin.'],
        ['Brand package', 'Logo, portraits, clinic photography and launch posts.'],
        ['Privacy built in', 'Consent-first cookie banner, privacy notice and terms.'],
      ],
      stack: ['Next.js', 'Payload CMS', 'PostgreSQL', 'Docker', 'Caddy'],
      cover: { type: 'browser', d: S('violeta-home-d'), m: S('violeta-home-m') },
      gallery: [
        { t: 'd', src: S('violeta-home-d'), label: 'Home' }, { t: 'd', src: S('violeta-services-d'), label: '/services' },
        { t: 'd', src: S('violeta-about-d'), label: '/about' }, { t: 'm', src: S('violeta-home-m') },
      ],
    },
    {
      id: 'reve', name: 'REVE', kind: 'Intimates brand', cats: ['store', 'web'], wip: true,
      color: '#7A1E2B', url: 'reve',
      chips: ['Discreet Mode', 'Guided sizing'],
      tagline: 'A women’s intimates brand for Pakistan — with a one-tap Discreet Mode.',
      lead: 'Built from zero for the Pakistan market, where privacy matters. Three signature features: Discreet Mode, Fit Memory and The Measure — a guided, bilingual way to find your size.',
      stats: [['3', 'signature features'], ['2', 'measurements to fit'], ['0', 'brand names on the parcel']],
      features: [
        ['Discreet Mode', 'One tap swaps imagery, names, the tab title and share previews to neutral.'],
        ['The Measure', 'Two measurements and a guided flow to the right size.'],
        ['Fit Memory', 'Remembers your size so the next order is one tap.'],
        ['Plain packaging', 'A promise shown across the site — no brand name on the parcel.'],
      ],
      stack: ['Next.js 16', 'React 19', 'TypeScript', 'PostgreSQL', 'Prisma', 'Redis'],
      cover: { type: 'browser', d: S('reve-home-d'), m: S('reve-measure-m') },
      gallery: [
        { t: 'd', src: S('reve-home-d'), label: 'Home' }, { t: 'd', src: S('reve-story-d'), label: '/story' },
        { t: 'd', src: S('reve-measure-d'), label: '/measure' },
        { t: 'm', src: S('reve-home-m') }, { t: 'm', src: S('reve-measure-m') },
      ],
    },
    {
      id: 'ahk', name: 'A&H Knives', kind: 'International store', cats: ['store', 'web', 'dash'], size: 'half', live: true,
      color: '#2B2620', url: 'ahknives.com',
      chips: ['Live · ahknives.com', 'Ships worldwide', 'Own admin'],
      tagline: 'Damascus steel, sold worldwide — live at ahknives.com.',
      lead: 'A premium, security-hardened storefront for knives, blades and swords, selling internationally. Headless Shopify handles card checkout; everything else — catalogue, guides, accounts and a full admin — is my own.',
      stats: [['Live', 'ahknives.com'], ['Worldwide', 'shipping'], ['1', 'file to rebrand']],
      features: [
        ['Damascus catalogue', 'Swords, knives, daggers, katanas and more, with rich product pages.'],
        ['Buying guides', 'What is Damascus steel, blade care, chef-knife buying guide — built for SEO.'],
        ['Customer accounts', 'Sign up, order history and order detail pages.'],
        ['Admin console', 'Products, categories, orders, customers, reviews, banners and site content.'],
        ['Safe card checkout', 'Headless Shopify checkout — PCI-compliant without touching card data.'],
        ['One-file rebrand', 'The whole site’s name, colours and copy come from a single config file.'],
      ],
      stack: ['Next.js 16', 'TypeScript', 'Tailwind v4', 'Framer Motion', 'Prisma'],
      link: { href: 'https://ahknives.com', label: 'Visit ahknives.com' },
      cover: { type: 'browser', d: S('live-ahk-home-d'), m: S('live-ahk-home-m') },
      gallery: [
        { t: 'd', src: S('live-ahk-home-d'), label: 'ahknives.com' }, { t: 'd', src: S('live-ahk-shop-d'), label: 'ahknives.com/shop' },
        { t: 'd', src: S('live-ahk-product-d'), label: 'Product page' }, { t: 'd', src: S('live-ahk-guide-d'), label: 'Buying guide' },
        { t: 'm', src: S('live-ahk-home-m') }, { t: 'm', src: S('live-ahk-product-m') },
      ],
    },
    {
      id: 'duakhana', name: 'Pakiza Duakhana', kind: 'Live store · my own platform', cats: ['store', 'web', 'dash'], size: 'half', live: true,
      color: '#3E5A1E', url: 'pakizaduakhana.com',
      chips: ['Live · pakizaduakhana.com', 'My own platform', 'Cash on delivery'],
      tagline: 'A real herbal-medicine business selling online across Pakistan.',
      lead: 'A herbal store — honey, oils and traditional remedies from Hakeem Abdullah Gujjar — selling across Pakistan with cash on delivery. It started on Shopify; today it runs on my own commerce platform: storefront, categories, guest checkout, blog and an analytics admin.',
      stats: [['Live', 'pakizaduakhana.com'], ['7', 'categories'], ['COD', 'across Pakistan']],
      features: [
        ['My own platform', 'Storefront, categories and product pages served by my Node + PostgreSQL + Redis platform — not a template.'],
        ['Guest checkout', 'Cash on delivery across Pakistan without making an account, plus ordering on WhatsApp.'],
        ['Ask the hakeem', 'One tap opens WhatsApp with a ready-made message asking the hakeem for advice.'],
        ['Analytics admin', 'Sales and visitor analytics with charts, in its own admin.'],
        ['Blog + video', 'Articles and a video from the hakeem.'],
        ['From Shopify to mine', 'Launched on Shopify with a full SEO pass, then moved onto my own platform.'],
      ],
      stack: ['Node', 'Express', 'PostgreSQL', 'Redis', 'Knex', 'EJS', 'Chart.js'],
      link: { href: 'https://pakizaduakhana.com', label: 'Visit the store' },
      cover: { type: 'browser', d: S('live-duakhana-home-d'), m: S('live-duakhana-home-m') },
      gallery: [
        { t: 'd', src: S('live-duakhana-home-d'), label: 'pakizaduakhana.com' },
        { t: 'd', src: S('live-duakhana-collection-d'), label: 'pakizaduakhana.com/category/digestive-general-health' },
        { t: 'd', src: S('live-duakhana-product-d'), label: 'Product page' },
        { t: 'm', src: S('live-duakhana-home-m') }, { t: 'm', src: S('live-duakhana-product-m') },
      ],
    },
    {
      id: 'bareeqs', name: 'The Bareeqs', kind: 'Private café · live', cats: ['web', 'lab'], size: 'half', live: true,
      color: '#3A2416', url: 'the-bareeqs',
      chips: ['Live', '12 rooms', 'No user table'],
      tagline: 'A private, candle-lit café for four friends — behind one spoken passphrase.',
      lead: 'A cosy online hangout for four people: votes, a shared ledger, ludo, a library, achievements, a hall of fame. You get in by speaking the phrase — no signup, no email, no user table.',
      stats: [['4', 'friends'], ['12', 'rooms'], ['0', 'user table']],
      features: [
        ['The door', '“You already know where you are.” Speak the phrase to unbolt it.'],
        ['The hall', 'The main room — notes, the counter, the snug and the library branch off it.'],
        ['Games', 'Ludo and votes, with achievements and a hall of fame.'],
        ['The ledger', 'A shared money ledger between the four friends.'],
        ['Server-side door', 'No passphrase — or hash of one — ever reaches the browser.'],
        ['Zero session flags', 'No client-side “logged in” flag anywhere in the code.'],
      ],
      stack: ['Next.js', 'SQLite', 'Security'],
      cover: { type: 'browser', d: S('bareeqs-gate-d'), m: S('bareeqs-gate-m') },
      gallery: [{ t: 'd', src: S('bareeqs-gate-d'), label: 'The door' }, { t: 'm', src: S('bareeqs-gate-m') }],
    },
    {
      id: 'gumgum', name: 'Gum-Gum', kind: 'Webcam effect', cats: ['lab'], size: 'half',
      color: '#3A1A0C', url: '',
      chips: ['Hand tracking', 'Try it'],
      tagline: 'Pinch, pull, and a rubber arm stretches out of you. Go on — drag the fist.',
      lead: 'Pinch your thumb and fingertip, drag your hand away, and a rubbery limb stretches from a frozen anchor to your live pinch point. Release and it snaps back with elastic overshoot — Luffy’s Gomu Gomu, in real time.',
      features: [
        ['Hand tracking', 'MediaPipe landmark models follow your fingers live through the webcam.'],
        ['Spring physics', 'The stretch and the snap-back overshoot are a real spring simulation.'],
        ['Cheek mode', 'Anchor the stretch to your face instead of your hand.'],
      ],
      stack: ['Python', 'OpenCV', 'MediaPipe'],
      cover: { type: 'gum' },
      gallery: [{ t: 'scene', html: '<canvas class="gum-canvas"></canvas><span class="gum-meter" style="color:#fff">stretch 1.0×</span>' }],
    },
    {
      id: 'walkie', name: 'Walkie-talkie', kind: 'Push-to-talk radio', cats: ['tool', 'lab'],
      color: '#123C31', url: 'walkie-talkie',
      chips: ['Peer-to-peer', 'No accounts'],
      tagline: 'Open the link, enter a PIN, hold the button, talk. Your friends hear you.',
      lead: 'Browser-based push-to-talk for up to five people. Voice goes peer-to-peer over WebRTC and never touches the server — no accounts, no database, no per-minute bills.',
      features: [
        ['PIN rooms', 'Every PIN is its own private room; no signup.'],
        ['Peer-to-peer voice', 'The server only introduces phones to each other.'],
        ['Any phone', 'Works in the browser; Docker deploy included.'],
      ],
      stack: ['WebRTC', 'Node', 'Docker'],
      cover: { type: 'phone', m: S('walkie-m') },
      gallery: [{ t: 'm', src: S('walkie-m') }, { t: 'd', src: S('walkie-d'), label: 'Desktop' }],
    },
    {
      id: 'leaner', name: 'leaner', kind: 'Code-health tool', cats: ['tool'],
      color: '#C9A227', url: 'leaner',
      chips: ['35+ languages', 'Zero dependencies'],
      tagline: 'A spell-checker for code: finds the bloat, the bugs, the leaks.',
      lead: 'One Python file with no dependencies. Point it at a project and it flags bloated, buggy and leaky code, then tidies it — built so people who code with AI can keep their projects clean.',
      features: [
        ['35+ languages', 'Reads almost any project.'],
        ['Private', 'Nothing leaves your computer, and it never edits without asking.'],
        ['Friendly', 'One-command installer, a plain-English manual and its own website.'],
      ],
      stack: ['Python', 'Static analysis'],
      cover: { type: 'browser', d: S('leaner-d'), m: S('leaner-m') },
      gallery: [{ t: 'd', src: S('leaner-d'), label: 'leaner website' }, { t: 'm', src: S('leaner-m') }],
    },
    {
      id: 'skyforge', name: 'Skyforge Armory', kind: 'Storefront', cats: ['store', 'web'],
      color: '#3B2A12', url: 'skyforge-armory',
      chips: ['6 pages', 'With admin'],
      tagline: 'Forged for the edge of tomorrow — a multi-page blade store with admin.',
      lead: 'A dark, cinematic multi-page storefront — home, shop, product, about, contact — plus an admin page, built with plain HTML, CSS and JavaScript.',
      stack: ['HTML', 'CSS', 'JavaScript'],
      cover: { type: 'browser', d: S('skyforge-d'), m: S('skyforge-m') },
      gallery: [{ t: 'd', src: S('skyforge-d'), label: 'Home' }, { t: 'm', src: S('skyforge-m') }],
    },
    {
      id: 'migration', name: 'migration-engine', kind: 'Support-ticket migration', cats: ['tool'], size: 'half',
      color: '#23397A', url: 'migration-engine',
      chips: ['Helpdesk tickets', 'Verification report'],
      tagline: 'Moves support tickets out of dying helpdesks — and proves nothing was lost.',
      lead: 'An engine for moving data out of SaaS tools that are shutting down. The first pack moves helpdesk tickets from a real, deliberately messy Zendesk export. The product isn’t the transfer — it’s the verification report.',
      features: [
        ['Drop an export', 'Upload a Zendesk export — zip, json, ndjson, csv or sql.'],
        ['See the report first', 'The full verification report is shown before you pay.'],
        ['Adapter packs', 'Adding a new source needs zero changes to the core engine.'],
        ['Loud failures', 'Every unfinished stage throws — silent data loss is the only unforgivable bug.'],
      ],
      stack: ['Node 22', 'TypeScript', 'PostgreSQL', 'Redis'],
      cover: { type: 'browser', d: S('migration-d'), m: S('migration-m') },
      gallery: [{ t: 'd', src: S('migration-d'), label: 'Upload' }, { t: 'm', src: S('migration-m') }],
    },
    {
      id: 'velvet', name: 'Velvet Edge', kind: 'Shop + owner dashboard', cats: ['store', 'web', 'dash'], size: 'half',
      color: '#6A1B2B', url: 'velvet-edge',
      chips: ['Shop', 'Owner dashboard', 'Double-click to open'],
      tagline: 'Nail tools from a Sialkot workshop — shop and dashboard in one double-click.',
      lead: 'A clickable shop and owner control panel for a manufacturer, deliberately packaged so the client opens a single file with a double-click — no internet, no install, no server.',
      features: [
        ['Full shop', 'Catalogue, product pages, bulk / own-brand orders, cart and checkout.'],
        ['Owner dashboard', 'Orders, bulk enquiries, stock and sales at a glance.'],
        ['Zero-install delivery', 'The whole thing opens from one file.'],
      ],
      stack: ['HTML', 'CSS', 'JavaScript', 'Node'],
      cover: { type: 'browser', d: S('velvet-dash-d'), m: S('velvet-site-m') },
      gallery: [
        { t: 'd', src: S('velvet-dash-d'), label: 'Owner dashboard' }, { t: 'd', src: S('velvet-site-d'), label: 'Shop' },
        { t: 'm', src: S('velvet-site-m') },
      ],
    },
    {
      id: 'yapgap', name: 'yapgap', kind: 'Self-improvement PWA', cats: ['app'],
      color: '#2A2A2A', url: 'yapgap',
      chips: ['Installable', 'Offline'],
      tagline: 'Build the man: career, mind and body, with daily accountability.',
      lead: 'An installable app with four pillars — Forge (motivation with an intensity dial), Taste, Read and Body. Runs with zero dependencies on Node’s built-in server and SQLite, and works offline.',
      stack: ['Node', 'SQLite', 'PWA', 'Capacitor'],
      cover: { type: 'phone', m: S('yapgap-m') },
      gallery: [{ t: 'm', src: S('yapgap-m') }, { t: 'd', src: S('yapgap-d'), label: 'Desktop' }],
    },
    {
      id: 'irfan', name: 'Irfan Sanitary', kind: 'Business website', cats: ['web'],
      color: '#5A3E22', url: 'irfan-sanitary',
      chips: ['Trade pricing'],
      tagline: 'Bulk rates for plumbers and builders in Gujranwala.',
      lead: 'A prototype for a sanitary-ware business: product range, bulk quotes for contractors, and a clear path to “send the list, get a quote”.',
      stack: ['HTML', 'CSS', 'JavaScript'],
      cover: { type: 'browser', d: S('irfan-d'), m: S('irfan-m') },
      gallery: [{ t: 'd', src: S('irfan-d'), label: 'Home' }, { t: 'm', src: S('irfan-m') }],
    },
    {
      id: 'cashclose', name: 'Shift Close', kind: 'Cash reconciliation', cats: ['tool', 'dash'],
      color: '#1E4E8C', url: 'cash-close',
      chips: ['PKR notes', 'History'],
      tagline: 'Count the drawer, match the sales, see the difference — end of every shift.',
      lead: 'A single-page tool for shops: enter note and coin counts, card and online totals, and it reconciles the shift and keeps the history.',
      stack: ['HTML', 'JavaScript'],
      cover: { type: 'browser', d: S('cashclose-d') },
      gallery: [{ t: 'd', src: S('cashclose-d'), label: 'Shift Close' }],
    },
    {
      id: 'quant', name: 'quant-tool', kind: 'Market analysis', cats: ['tool'], size: 'half',
      color: '#0F3B2E', url: '',
      chips: ['Backtests', 'Charts + report'],
      tagline: 'Backtests trading strategies from price history — Sharpe, CAGR, drawdown.',
      lead: 'Point it at a CSV of historical prices and it computes returns, volatility, correlation, an RSI mean-reversion backtest and a moving-average crossover backtest — then writes charts and a report. Analysis of the past, not advice.',
      stack: ['Python', 'Pandas', 'Matplotlib'],
      cover: { type: 'type', title: 'Sharpe · CAGR · Max DD', sub: 'RSI + MA crossover backtests' },
    },
    {
      id: 'umar', name: 'Umar Sanitary', kind: 'Website + admin', cats: ['web', 'dash'], size: 'half',
      color: '#2D5C73', url: 'umar-sanitary',
      chips: ['Invoices', 'Analytics'],
      tagline: 'Tiles, ceramics and sanitary ware — site, invoices and analytics.',
      lead: 'A product site for a sanitary-ware business — tiles by size, ceramics, sanitary, projects — with an admin for products, customers, invoices, enquiries and sales analytics.',
      features: [
        ['Catalogue', 'Tiles by size and type, ceramics, sanitary and project showcases.'],
        ['Invoices', 'Create and print invoices from customer records.'],
        ['Analytics', 'Sales and enquiry analytics in the admin.'],
      ],
      stack: ['Next.js', 'TypeScript', 'Prisma', 'Cloudinary'],
      cover: { type: 'type', title: 'Tiles. Ceramics. Sanitary.', sub: 'Site · invoices · analytics' },
    },
  ];
})();
